import type { TemplateDefinition } from '../types';

export const MASTER_TEMPLATES: TemplateDefinition[] = [
  // 1. ATS Category
  {
    id: 'ats-classic',
    name: 'ATS Classic Clean',
    category: 'ATS',
    description: 'Ultra-safe single-column layout optimized for 100% ATS parser fidelity across Taleo, Workday, and Greenhouse.',
    fontFamily: 'font-sans',
    headerFontFamily: 'font-sans',
    primaryColor: '#0f172a',
    secondaryColor: '#334155',
    accentColor: '#0284c7',
    backgroundColor: '#ffffff',
    layout: 'single-column',
    headerStyle: 'left-aligned',
    sectionDivider: 'subtle-line',
    bulletStyle: 'disc',
    fontSizeBase: 'text-sm',
    spacingDensity: 'compact',
    atsSafe: true,
    tags: ['ats-friendly', 'single-column', 'clean', 'standard'],
  },
  {
    id: 'ats-standard',
    name: 'ATS Strict Monospace-Clear',
    category: 'ATS',
    description: 'High-contrast typography with zero decorative artifacts, engineered for maximum scanner compatibility.',
    fontFamily: 'font-sans',
    headerFontFamily: 'font-sans',
    primaryColor: '#111827',
    secondaryColor: '#374151',
    accentColor: '#4b5563',
    backgroundColor: '#ffffff',
    layout: 'single-column',
    headerStyle: 'left-aligned',
    sectionDivider: 'solid-line',
    bulletStyle: 'hyphen',
    fontSizeBase: 'text-sm',
    spacingDensity: 'compact',
    atsSafe: true,
    tags: ['high-readability', 'standard-fonts', 'ats-proven'],
  },
  // 2. Modern Category
  {
    id: 'modern-slate',
    name: 'Modern Slate & Indigo',
    category: 'Modern',
    description: 'Sleek tech-forward layout featuring elegant typography, balanced negative space, and refined section headers.',
    fontFamily: 'font-sans',
    headerFontFamily: 'font-sans',
    primaryColor: '#0f172a',
    secondaryColor: '#475569',
    accentColor: '#4f46e5',
    backgroundColor: '#ffffff',
    layout: 'single-column',
    headerStyle: 'minimal',
    sectionDivider: 'accent-bar',
    bulletStyle: 'disc',
    fontSizeBase: 'text-sm',
    spacingDensity: 'normal',
    atsSafe: true,
    tags: ['tech', 'startups', 'modern-sans'],
  },
  {
    id: 'modern-emerald',
    name: 'Modern Emerald Growth',
    category: 'Modern',
    description: 'Fresh emerald accents paired with structured metadata badges, favored by high-growth venture scale startups.',
    fontFamily: 'font-sans',
    headerFontFamily: 'font-sans',
    primaryColor: '#064e3b',
    secondaryColor: '#065f46',
    accentColor: '#059669',
    backgroundColor: '#ffffff',
    layout: 'single-column',
    headerStyle: 'left-aligned',
    sectionDivider: 'subtle-line',
    bulletStyle: 'disc',
    fontSizeBase: 'text-sm',
    spacingDensity: 'normal',
    atsSafe: true,
    tags: ['emerald', 'fintech', 'venture'],
  },
  // 3. Professional Category
  {
    id: 'professional-executive',
    name: 'Corporate Executive Navy',
    category: 'Professional',
    description: 'Authoritative deep navy palette with centered executive header, suited for Directors, VPs, and Enterprise leaders.',
    fontFamily: 'font-serif',
    headerFontFamily: 'font-serif',
    primaryColor: '#1e293b',
    secondaryColor: '#334155',
    accentColor: '#0369a1',
    backgroundColor: '#ffffff',
    layout: 'single-column',
    headerStyle: 'centered',
    sectionDivider: 'solid-line',
    bulletStyle: 'disc',
    fontSizeBase: 'text-sm',
    spacingDensity: 'normal',
    atsSafe: true,
    tags: ['executive', 'board', 'enterprise'],
  },
  {
    id: 'professional-charcoal',
    name: 'Chartered Charcoal',
    category: 'Professional',
    description: 'Conservative monochrome aesthetic designed for finance, management consulting, and legal roles.',
    fontFamily: 'font-serif',
    headerFontFamily: 'font-sans',
    primaryColor: '#18181b',
    secondaryColor: '#27272a',
    accentColor: '#52525b',
    backgroundColor: '#ffffff',
    layout: 'single-column',
    headerStyle: 'bordered',
    sectionDivider: 'subtle-line',
    bulletStyle: 'square',
    fontSizeBase: 'text-sm',
    spacingDensity: 'compact',
    atsSafe: true,
    tags: ['finance', 'consulting', 'monochrome'],
  },
  // 4. Technical Category
  {
    id: 'technical-terminal',
    name: 'Technical Systems Architect',
    category: 'Technical',
    description: 'Tailored for software engineers, SREs, and DevOps architects with emphasized tech-stacks and clean dividers.',
    fontFamily: 'font-mono',
    headerFontFamily: 'font-sans',
    primaryColor: '#09090b',
    secondaryColor: '#27272a',
    accentColor: '#2563eb',
    backgroundColor: '#ffffff',
    layout: 'single-column',
    headerStyle: 'left-aligned',
    sectionDivider: 'accent-bar',
    bulletStyle: 'hyphen',
    fontSizeBase: 'text-sm',
    spacingDensity: 'compact',
    atsSafe: true,
    tags: ['developer', 'sre', 'devops', 'clean-code'],
  },
  {
    id: 'technical-split-left',
    name: 'Technical Split Sidebar',
    category: 'Technical',
    description: 'Dual-pane architecture with left sidebar highlighting skills, links, and certifications alongside experience stream.',
    fontFamily: 'font-sans',
    headerFontFamily: 'font-sans',
    primaryColor: '#0f172a',
    secondaryColor: '#334155',
    accentColor: '#3b82f6',
    backgroundColor: '#ffffff',
    layout: 'two-column-left',
    headerStyle: 'banner',
    sectionDivider: 'subtle-line',
    bulletStyle: 'disc',
    fontSizeBase: 'text-xs',
    spacingDensity: 'compact',
    atsSafe: false,
    tags: ['two-column', 'visual-sidebar', 'portfolio'],
  },
  // 5. Fresher / Graduate Category
  {
    id: 'fresher-academic',
    name: 'University Scholar / Entry',
    category: 'Fresher',
    description: 'Prioritizes academic credentials, honors, coursework, and technical projects for recent graduates and interns.',
    fontFamily: 'font-sans',
    headerFontFamily: 'font-sans',
    primaryColor: '#1e1b4b',
    secondaryColor: '#312e81',
    accentColor: '#4338ca',
    backgroundColor: '#ffffff',
    layout: 'single-column',
    headerStyle: 'centered',
    sectionDivider: 'subtle-line',
    bulletStyle: 'disc',
    fontSizeBase: 'text-sm',
    spacingDensity: 'normal',
    atsSafe: true,
    tags: ['college', 'grad', 'entry-level', 'internship'],
  },
  // 6. Executive Category
  {
    id: 'executive-prestige',
    name: 'Prestige Boardroom Gold',
    category: 'Executive',
    description: 'Sophisticated typography pairing with subtle warm gold accents, designed for C-level and advisory board resumes.',
    fontFamily: 'font-serif',
    headerFontFamily: 'font-serif',
    primaryColor: '#1c1917',
    secondaryColor: '#292524',
    accentColor: '#b45309',
    backgroundColor: '#ffffff',
    layout: 'single-column',
    headerStyle: 'bordered',
    sectionDivider: 'solid-line',
    bulletStyle: 'disc',
    fontSizeBase: 'text-sm',
    spacingDensity: 'spacious',
    atsSafe: true,
    tags: ['c-level', 'vp', 'board', 'prestige'],
  },
  // 7. Creative Category
  {
    id: 'creative-canvas',
    name: 'Creative Product Designer',
    category: 'Creative',
    description: 'Distinctive visual hierarchy with prominent portfolio links, curated for UX/UI designers and product managers.',
    fontFamily: 'font-sans',
    headerFontFamily: 'font-sans',
    primaryColor: '#18181b',
    secondaryColor: '#3f3f46',
    accentColor: '#db2777',
    backgroundColor: '#ffffff',
    layout: 'single-column',
    headerStyle: 'banner',
    sectionDivider: 'accent-bar',
    bulletStyle: 'disc',
    fontSizeBase: 'text-sm',
    spacingDensity: 'normal',
    atsSafe: true,
    tags: ['design', 'product', 'creative'],
  },
];

export function getFullTemplateCatalog(): TemplateDefinition[] {
  const generated: TemplateDefinition[] = [...MASTER_TEMPLATES];

  const PALETTES = [
    { name: 'Sapphire', primary: '#0f172a', accent: '#0284c7' },
    { name: 'Amethyst', primary: '#1e1b4b', accent: '#7c3aed' },
    { name: 'Rose', primary: '#27272a', accent: '#e11d48' },
    { name: 'Teal', primary: '#134e4a', accent: '#0d9488' },
    { name: 'Amber', primary: '#1c1917', accent: '#d97706' },
    { name: 'Steel', primary: '#1e293b', accent: '#64748b' },
  ];

  const FONTS = [
    { name: 'Inter System', font: 'font-sans', head: 'font-sans' },
    { name: 'Serif Classic', font: 'font-serif', head: 'font-serif' },
    { name: 'Mono Code', font: 'font-mono', head: 'font-sans' },
  ];

  for (const base of MASTER_TEMPLATES) {
    for (const pal of PALETTES) {
      for (const font of FONTS) {
        const comboId = `${base.id}-${pal.name.toLowerCase()}-${font.name.split(' ')[0].toLowerCase()}`;
        if (!generated.some((t) => t.id === comboId)) {
          generated.push({
            ...base,
            id: comboId,
            name: `${base.name} (${pal.name} • ${font.name})`,
            accentColor: pal.accent,
            primaryColor: pal.primary,
            fontFamily: font.font,
            headerFontFamily: font.head,
            tags: [...(base.tags || []), pal.name.toLowerCase()],
          });
        }
      }
    }
  }

  return generated;
}
